### ISSUE TITLE
"fork"

### ISSUE THREAD

**Issue by JessicaMulein** [chrisakroyd/random-seedable#3]
I am using your code in a mono-repo and I've forked it only to resolve some incomplete typing issues.
I don't really want to maintain a fork.
Nevertheless, if you want to backport anything out of my "fork"- it is located https://github.com/Digital-Defiance/nx-monorepo/tree/main/digital-defiance/libs/random-seedable-ts

**Comment by JessicaMulein** [comment]
abandoned.

**Comment by chrisakroyd** [comment]
Totally understand. Would you be able to explain these incomplete type issues? I've been meaning to do a TypeScript rewrite since this library got more popular, at the moment both the types and documentation are generated from docstring and I'm happy to deal with it now if you're willing to explain the issue.
